name: Build and Deploy MCP Server to Azure App Service

on:
  push:
    paths:
      - 'LunchTimeMCP/MCP.sse/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0

    - name: Cache .NET packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: nuget-packages-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          nuget-packages-${{ runner.os }}-

    - name: Build the .NET Web API project
      run: dotnet build LunchTimeMCP/MCP.sse/MCP.sse.csproj

    - name: Cache build artifacts
      uses: actions/cache@v3
      with:
        path: ./publish
        key: build-artifacts-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          build-artifacts-${{ runner.os }}-

    - name: Publish the .NET Web API project
      run: dotnet publish LunchTimeMCP/MCP.sse/MCP.sse.csproj -c Release -o ./publish

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: bipulmcp
        publish-profile: ${{ secrets.MCP_SERVER_PUBLISH_PROFILE }} # You need to set this secret in your repository settings
        package: ./publish